### ISSUE TITLE
Missing Gamemode

### ISSUE THREAD

**Issue by Gensokian** [Hypnootize/hypnotize-hud#10]
In stock tf2 when connecting to a map, you can see the gamemode which the map is playing. It's quite confusing if your going 5gorge 5cp or 2cp.

![image](https://user-images.githubusercontent.com/9213561/40255419-5c889360-5ae7-11e8-93e8-69b557ab5393.png)

**Comment by Gensokian** [comment]
Adittion: I also noticed that the duel wins are not beeing displayed either; I don't need it, just some people might like it

**Comment by Hypnootize** [comment]
I added the gamemode, and I don't really like having the duels on the load screen so I'm probably never gonna add them.
