### ISSUE TITLE
Toggleconsole button

### ISSUE THREAD

**Issue by Gensokian** [Hypnootize/hypnotize-hud#12]
Just a little suggestion which isn't that significant;

Basically a little "Toggleconsole" command button which toggles the console (Who'd guessed that?)

If ya want to; i added a selfmade one as a png and vtf

https://quickfileshare.org/4hy/console_icon.png
https://quickfileshare.org/4hz/console_icon.vtf

(I hope that works with that website, normally never upload stuff on quick sites n stuff... wasn't able to upload the vtf here either...)

![console icon](https://user-images.githubusercontent.com/9213561/40579098-93b5d69c-6120-11e8-8662-3fb63b157db0.png)

(also the icon is white sooo it doesn't display properly here)

**Comment by Hypnootize** [comment]
This looks actually really good gj! 👍 I'll see if i can maybe implement it in the future  (I just need to find the time and effort to remake the other icons as images as well 😆 soon...soon...)
