### ISSUE TITLE
the hud isnt loading

### ISSUE THREAD

**Issue by LennyMcLennington** [Hypnootize/hypnotize-hud#14]
updated hud to latest version,
hud stopped loading

tried another hud, that worked. pls fix i love the hud but for now i will just have to use an older commit i guess

**Comment by Gensokian** [comment]
Have you extracted the correct folder? Don't extract the "Hypnotize-Hud-master" folder. You need to extract the "hypnotize hud" folder directly into the custom folder. Otherwise you may want to check if you have sv pure accidentally configured to allow nothing...

**Comment by LennyMcLennington** [comment]
yes i did and no it wasnt i tried another hud and that worked fine so no sv pure

**Comment by Hypnootize** [comment]
I didn't work on this hud for quite some time sry, I was using this the last 2 days and it seems fine. If you are still using my hud and you haven't fixed the problem yet can i ask what system are you on like windows mac linux?
