### ISSUE TITLE
Map stamp suggestion

### ISSUE THREAD

**Issue by Gensokian** [Hypnootize/hypnotize-hud#15]
![2018-06-05 19_15_58-greenshot](https://user-images.githubusercontent.com/9213561/41054472-c4861f6a-69be-11e8-875f-3f7d2dbc13b3.jpg)

When checking out on the shop you cannot decline the offer of getting some map stamps.
Workaround so far is to cancel the transaction and restarting the purchase.

**Comment by Hypnootize** [comment]
That should be fixed now!
