### ISSUE TITLE
Team/class icons on top are...ugly, in the latest update.

### ISSUE THREAD

**Issue by battleboner** [Hypnootize/hypnotize-hud#16]
https://i.imgur.com/fs0stTE.png

Updating to the latest version of your gorgeous HUD did this. I've spent the last 45 minutes searching for the name of the file/element that controls this, but found nothing. I even tried copying every .res file from the old versions' `/resource/ui` to the new one, with no luck. 

If this was intentional, it'd be awesome if you could let me know which file(s) to edit/replace to revert it to the old style. For now I'll just stick with the outdated version.

**Comment by Hypnootize** [comment]
I reverted it to how it used to be, the name of the file is hudmatchstatus.res > "TeamStatus" just in case 😃
