### ISSUE TITLE
I found a visual Bug! (atleast i think)

### ISSUE THREAD

**Issue by dbuBBle** [Hypnootize/hypnotize-hud#2]
So I decided to give a try to your actual hud and so far I LOVE IT <3
Anyway found this when I was crafting some scrap.
https://i.imgur.com/YsGxhTD.jpg
Has you can see, there's something around the box.

**Comment by Hypnootize** [comment]
Thank you so much! I was aware of these bugs (doesn't only happen on the crafting thing I think) sadly I have no idea if there is any file i can edit to fix all of these confirm messages. I wanted to add a full screen background which usually fixes the problem like i did for the others :(

**Comment by dbuBBle** [comment]
No problem :)
