### ISSUE TITLE
Bunch of tiny little hud issues at once.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [Hypnootize/hypnotize-hud#21]
So, I´ve came back to my first loves, and installed that hud again on my newly installed linux Team Fortress 2. And outside of the many graphical issues due to that particular version, something else has been spotted by my eyes.
![20190323175156_1](https://user-images.githubusercontent.com/13170204/54869677-74b88f00-4d9c-11e9-81c7-15d5d680298e.jpg)
The first being that taunt menu text on the right, sadly overlapping on the contracts text. A possible solution to that would be to move that contract text a bit highter.
The second being the 3D character on the bottom left, having the unusual effects cutted. While i expect that no real solutions could be made for that part, if one would exist, it would allow it to draw a bit more the top of the characters, in order to display it completly, as this is even more visible with some couples of higher tiers unusual effects.
![20190323175750_1](https://user-images.githubusercontent.com/13170204/54869678-74b88f00-4d9c-11e9-9cb5-d632ddeed02a.jpg)
The last being something that i think occurs with every custom hud´s, but i would still try to report it. Being the placed stickies counter appearing kind of broken, before going back to normal when it updates.

**Comment by Hypnootize** [comment]
I fixed both the player model getting cut off and the taunt menu overlapping the contracts. About the stickies couter being broken I'm almost 100% sure that there is no fix as it happens even in the default hud, anyway it fixes by itself as soon as you shoot a sticky so its not that big of a problem i guess.

Thank you for reporting these!
