### ISSUE TITLE
Problem Medic In MVM

### ISSUE THREAD

**Issue by RunawaySheld123** [Hypnootize/hypnotize-hud#24]
![20191105074835_1](https://user-images.githubusercontent.com/26026554/68175486-5bc3bd80-ffbc-11e9-9321-5cdf655536a8.jpg)

There A Problem For A Medic Energy Shield

**Comment by Hypnootize** [comment]
Should be fixed now, still not the prettiest fix I could have done but thats the max I can do without compromising anything else
