### ISSUE TITLE
Icons are too large

### ISSUE THREAD

**Issue by alliumm** [Hypnootize/hypnotize-hud#26]
Every icon I have seen has this behavior. This results in many being cut off and the others being misaligned.
I am using linux at 1080p, I don't know if this happens on other resolutions or operating systems.

The biggest issue on the main menu is the casual rank being way too large. Every other icon is also slightly too large, causing cut offs in the bottom left and misaligned icons everywhere else.
![20200325223336_1](https://user-images.githubusercontent.com/33610620/77622490-408b2780-6f36-11ea-874b-9814d82fad3d.jpg)
It is especially noticeable in the pause menu.
![20200325223419_1](https://user-images.githubusercontent.com/33610620/77622836-e9d21d80-6f36-11ea-97be-4040379b2268.jpg)

**Comment by Hypnootize** [comment]
Hey, as far as I know linux does scale fonts differently from windows so yes thats the main problem (resolution shouldn't really matter in this case) sadly I can't really test it so its kinda hard to fix it for me.

You could try resizing the fonts with something like fontforge, it should't be too hard, I can drive it through it if you want to give it a try!

**Comment by alliumm** [comment]
That would be great! I just tried scaling it myself and it spat out a bunch of errors.
Does this mean that every other font is also slightly too large?

Also, it seems like the level counter is almost twice as large as it should be instead of just a little larger. Is this the same issue?

**Comment by Hypnootize** [comment]
Yes the level font seems a weird one to me as well I'm not really sure whats happening there, it seems almost double the size it should be.
 
Anyway I got various sources telling me multiple times in the past that if I wanted to get my fonts to wrok properly on linux I had to resize them for about 25% of their windows size so I did try resizing these icons font and the level font but i have no way to test it.

If you ever wanna give these a try just replace them in the resource/scheme/fontfiles folder [dl](https://www.dropbox.com/s/ehttcq2eh389f6u/HypnotizeHUD%20Linux%20Fonts.rar?dl=0)

**Comment by alliumm** [comment]
It looks like the icons are perfectly sized! Thank you!
However, the size of the level font didn't change. I was able to resize it correctly by changing the size of "Avenir Numbers" to 9 in ./resource/scheme/Fonts.res

**Comment by HurricanePootis** [comment]
If you want to resize your fonts manually in the future, download fontforge, which should be available for most major distributions. Once you opened up the font file in font forge, Ctrl + A all of the characters, click the Element tab, and Transform. Change from Move, to Scale Uniformly, and scale down to 75%. Then, click on File, and Generate Fonts. Make sure you have selected the font file format same as the original, and same name.
