### ISSUE TITLE
Missing playericon and blank box on killcam

### ISSUE THREAD

**Issue by Gensokian** [Hypnootize/hypnotize-hud#27]
When dying to an enemy that also dies before the freezecam, the little box with the health information is just completely blank. Also it is missing the default player-icon which is just in stock TF2. (Personal preference, but I like it neither the less) :)
![image](https://user-images.githubusercontent.com/9213561/78306671-3ecbf000-7544-11ea-8774-5b7ad449850c.png)

My recommendation would be a tiny rewrite of the box, something along the lines of this maybe?
![image](https://user-images.githubusercontent.com/9213561/78306351-771efe80-7543-11ea-9f7f-40cfdc7f8d52.png)

Also a tiny nitpick is that the whole panel isn't completely centered
![image](https://user-images.githubusercontent.com/9213561/78306950-f6f99880-7544-11ea-9789-15a81e56e43f.png)

**Comment by Hypnootize** [comment]
I wanted it to be as clean and small as possible thats why it only shows name and health, I can try making the health background disappear when the killer is also dead (which might not be achievable) but other than that i wouldn't change much, I kinda like how it is.

Also its really off center, yikes, I'll center it for sure on the next update.
