### ISSUE TITLE
Vaccinator & Diguise Panel in MvM

### ISSUE THREAD

**Issue by adri-hub** [Hypnootize/hypnotize-hud#28]
### Vaccinator :

All 4 charge meters were slightly out of center. Same for the stock one.

![vacc](https://user-images.githubusercontent.com/57393255/82448967-c5b03a00-9aaa-11ea-9e03-4f574e30dc83.png)

[HudMedicCharge.zip](https://github.com/Hypnootize/Hypnotize-Hud/files/4657056/HudMedicCharge.zip)

### Diguise Panel in MvM :

![mvmspymoney](https://user-images.githubusercontent.com/57393255/82450057-7d921700-9aac-11ea-9cd9-79be4547b275.png)

[DiguiseStatusPanel+Currency.zip](https://github.com/Hypnootize/Hypnotize-Hud/files/4657050/DiguiseStatusPanel%2BCurrency.zip)

**Comment by Hypnootize** [comment]
I was checking this out and the Vaccinator being slightly out of center is a problem that only occurs on lower resolutions, it looks perfect on 1920x1080 which is by far the most used resolution.

Thats what it normally looks like vs what it would look like with your fix:

![Immagine](https://user-images.githubusercontent.com/19785551/86954179-d0f01f80-c155-11ea-99ac-5030714bef71.png)
So its just a resolution scaling problem I can't do much about sadly

About the disguise pannel I'm not a fan of what it looks like with and without the fix, I'm probably going to rework it in some way soon.
