### ISSUE TITLE
Confirm Dialogs are bugged

### ISSUE THREAD

**Issue by b7a** [Hypnootize/hypnotize-hud#3]
They show up like this for me: https://imgur.com/WiUMHSK
Is this on my end, or is it a general issue? And if it's just me, how do I go about fixing it?

**Comment by Hypnootize** [comment]
Its a general issue, valve changed them in the last updated and now the label that says "you will not able to rejoin etc..." is acting weird like everytime i want to edit the ypos it just break everything else somehow.
I guess they hardcoded it in some way so it doesn't get bugged if that label gets really big in certains confirm messages. Anyway i tried and failed everytime i wanted to fix it for now :\
