### ISSUE TITLE
Crosshair

### ISSUE THREAD

**Issue by Scoutman01** [Hypnootize/hypnotize-hud#30]
you should put the crosshair in hudplayerclass instead of hudlayout so it doesn't appear on freeze panel,spectator,class selection
![20200819205106_1](https://user-images.githubusercontent.com/50184129/90678270-c2ba1680-e25e-11ea-8dfa-4db5f129deb5.jpg)

**Comment by Hypnootize** [comment]
I tend to forget about this since it never really bothered personally me but there is probably lot of users that don't like the crosshairs showing everywhere so might as well move them to the playerclass 👍
