### ISSUE TITLE
heya i cant comment in the steam page cuz im freemium but i need help

### ISSUE THREAD

**Issue by SlavicSquire** [Hypnootize/hypnotize-hud#31]
how do i enable box-style animations in hypnotize HUD?

**Comment by Hypnootize** [comment]
Hey, all you do is navigate to customizations/health & ammo box overrides and from that folder you want to copy both resource and scripts folder, now go back to the main HypnotizeHud folder _(so the one that contains the material,resource,scripts and info.vdf)_ and you want to paste both previously copied folders there and when windows asks you if you want to replace the files you want to select yes.
I Hope that helps!

**Comment by SlavicSquire** [comment]
Thank you so much!!!!! :DDD
