### ISSUE TITLE
Clicking the notification counter should open the notifications aswell

### ISSUE THREAD

**Issue by Gensokian** [Hypnootize/hypnotize-hud#35]
I really like the new long notification button, yet I have one gripe with it.
I intuitively click the shiny numbered button, yet nothing happens.

**Comment by Hypnootize** [comment]
This should be finally fixed in the new release: https://github.com/Hypnootize/hypnotize-hud/releases/tag/V1.1
I forgot to do that previously, it was just a matter of turning of the mouse input for the notification number.
