### ISSUE TITLE
Publish releases for more stability with HUD users. 

### ISSUE THREAD

**Issue by DGKSK8LIFE** [Hypnootize/hypnotize-hud#36]
Been using your HUD for a long time. Love it. Would prefer if you had stable releases using Github's release system though. Ty

**Comment by Hypnootize** [comment]
Yes I should have probably started doing releases a long time ago actually, I always forget about it but the main thing I never did is that I was felt like there wasn't stable version at any point until I redesigned the entire HUD recently. 
Now that most bugs and improvements are out of the way I can proabably do a release of the current version and hopefully I don't forget to keep doing it in the future. :D

**Comment by DGKSK8LIFE** [comment]
Thanks! Issue closed.
