### ISSUE TITLE
[4k display] Larger chatbox & turn off name headers

### ISSUE THREAD

**Issue by agiantwhale** [Hypnootize/hypnotize-hud#41]
I'm looking for a way to do two things:

* Make chat box larger on 4k display (3840 * 2160)
  * "tall" option in "ChatFont" isn't respected.
* Turn off name headers on spawn (or move it higher, overlaps health bar)

Thanks!

![markuphero-jEjvIbDNQ6pz9ucCNySy-1](https://user-images.githubusercontent.com/3136207/122833386-bd27c580-d2a1-11eb-9482-775a6a44b34e.png)

**Comment by Hypnootize** [comment]
Hey!

For the chat font you should be able to change that from `Resource/ChatScheme.res > "ChatFont"` make sure you use the fifth definition as that's the one that should cover 4K, precisely this line:
https://github.com/Hypnootize/hypnotize-hud/blob/master/resource/chatscheme.res#L383 

To turn off the teammates names on respawn you can simply navigate to `Scritps/Layouts/Layout_Default.res > HudSpectatorExtras` and set both `wide` and `tall` to `0`, right there:
https://github.com/Hypnootize/hypnotize-hud/blob/master/scripts/layouts/layout_default.res#L1465-L1466
