### ISSUE TITLE
F on the side of my screen when i repawn

### ISSUE THREAD

**Issue by ducky0** [Hypnootize/hypnotize-hud#46]
screenshot

https://imgur.com/zJGb20j

**Comment by Hypnootize** [comment]
It seems to be working fine for me and I don't see anything in the file that could cause that.
Having multiple `spectator.res` files inside custom could possibly cause that, could be part of a mod or even another HUD that you forgot to take out. That's the only thing I can think of as of now.

Edit: I recently pushed a commit that gets rid of the proportional values used for the respawn label as the game might not like that, hopefully that fixes it for everyone!
