### ISSUE TITLE
Missing advanced Stats

### ISSUE THREAD

**Issue by Gensokian** [Hypnootize/hypnotize-hud#5]
Headshot counter, captures healing and so on on the bottom of the scoreboard seem to be disabled. Servertime in the upper left? Also servername not visible.

Really enjoying the hud though, GREAT WORK!

![unbenannt](https://user-images.githubusercontent.com/9213561/39273368-e37f4aa0-48de-11e8-915d-9d79133d6b30.jpg)

**Comment by Hypnootize** [comment]
Thank you! I'm working on a scoreboard with all the stats, I'll add it as a customization soon.
The servertime on the top left is intentional as i wanted it to look like the normal timer, last the server label will be added soon as well (i completely forgot about it somehow).

**Comment by Gensokian** [comment]
I just thought that that could look pretty sleek when done correctly
