### ISSUE TITLE
health and ammo

### ISSUE THREAD

**Issue by miyho** [Hypnootize/hypnotize-hud#55]
Just wanted to know how to make them bigger and a little more away from the crosshair, similar to broeselhud (the last damage done numbers aswell), i know its not really an issue but i dont know other ways to contact other than that.

**Comment by Hypnootize** [comment]
The files you want to edit are HudAmmoWeapons.res and HudPlayerHealth_Normal.res, for the font size you want to edit the `"font"` value for ["PlayerStatusHealthValue"](https://github.com/Hypnootize/hypnotizehud/blob/master/resource/ui/hudplayerhealth_normal.res#L50-L51) and ["PlayerStatusHealthValueShadow"](https://github.com/Hypnootize/hypnotizehud/blob/master/resource/ui/hudplayerhealth_normal.res#L74-L75) for the health and same thing for the ammo, you want to edit every `font` value you find in the file. You can check what fonts you can use inside [fonts.res](https://github.com/Hypnootize/hypnotizehud/blob/master/resource/scheme/fonts.res#L11-L273) and if the size you are looking for is not there then you can simply create one.

For the positioning there is an anchor element you can use in both files ["HEALTHAnchor"](https://github.com/Hypnootize/hypnotizehud/blob/master/resource/ui/hudplayerhealth_normal.res#L21-L34) for the health and [AMMOAnchor](https://github.com/Hypnootize/hypnotizehud/blob/master/resource/ui/hudammoweapons.res#L3-L16) for the ammo, you can use these two element to move health and ammo wherever you want.

**Comment by miyho** [comment]
How can i make a new one?
the max size is 40 (Game 40), i tried "Size 44" but it goes back to the rubik default font, and i have surface font
i tried making a new one named "Game 50" and changed the tall value to 50 but it didnt work

**Comment by Hypnootize** [comment]
Inside fonts.res you can create a new one like
```
"Game 50"
{
	"1"
	{
		"name"			"Rubik SemiBold"
		"tall"			"50"
		"antialias"		"1"
	}
}
```
And then you want to also add it inside the `resource/fonts/alternative_fonts/fonts_surface.res` to change it's `"name"` like:
```
"Game 50"
{
	"1"
	{
		"name"			"surface-medium"
	}
}
```
once you have that set up you can use it inside the ammo and health files

**Comment by miyho** [comment]
ooooohhhh, thanks, i only did the first part lol

**Comment by miyho** [comment]
yo i had to make one called "Game 50 Blur" too, and now all text on the hud is invisible oops

**Comment by miyho** [comment]
game is also crashing when i try to queue

**Comment by miyho** [comment]
bruh nvm ill use the normal text size thanks for having patience with my dumb ass
