### ISSUE TITLE
issues and bugs with the 1.6 release

### ISSUE THREAD

**Issue by LuhGeek4044** [Hypnootize/hypnotize-hud#56]
Crafting icons change to default icons when in-game **( only present in sv_pure 1 servers )**
![image](https://github.com/Hypnootize/hypnotizehud/assets/141937232/bc516cab-5937-42c0-869e-9763ca155c15)
![image](https://github.com/Hypnootize/hypnotizehud/assets/141937232/6005acdf-171d-409c-84ef-f6d38f83d0b2)

Arrow icons in map selection change to default icons when in-game **( only present in sv_pure 1 servers )**
![image](https://github.com/Hypnootize/hypnotizehud/assets/141937232/bd1b32f6-da56-4a16-9969-c991504356a9)
![image](https://github.com/Hypnootize/hypnotizehud/assets/141937232/a4d95a2b-8779-423d-a4ff-7576910bc922)

Scroll up and down icons in map intro screen changes to default **( only present in sv_pure 1 servers )**
![image](https://github.com/Hypnootize/hypnotizehud/assets/141937232/ce92a005-2347-496b-9ef1-4444fea86bf0)
![image](https://github.com/Hypnootize/hypnotizehud/assets/141937232/284b8b5d-7f6e-41fa-99f6-5485b9c273d0)

Level twitches up and down when opening the menu in-game
![image](https://github.com/Hypnootize/hypnotizehud/assets/141937232/8374b488-f035-49c5-839f-cbfb1c1c73dd)
![image](https://github.com/Hypnootize/hypnotizehud/assets/141937232/4e469dd4-7144-448e-bb46-45563ab7966b)

Level progress bar is overlapping with the queue bar/nofication **( only present on 4:3 resolution )**
![image](https://github.com/Hypnootize/hypnotizehud/assets/141937232/46efc105-1f2f-413e-9695-38c0d0627180)

**Comment by Hypnootize** [comment]
As far as I'm aware there isn't a way to make the craft filters icons and the expand/retract icons work with sv_pure, but I still decided to implement them anyway to at least have them offline. I should be able to make the scrollbar work everywhere however, I simply haven't had the chance to implement it yet, will be there soon.
The level twitching is a game thing, it happens with the default HUD as well so I assume it's not HUD related, and to be fair is barely noticeable.
I wasn't aware of the level bar overlapping, I'll see if I can maybe tweak it a little bit for 4:3

**Comment by LuhGeek4044** [comment]
I'm glad your working on a fix but i happen to stumble on another one theres pixel gaps in the top and bottom bar in the menu, they may not be visible in these images because they were screen shotted on windowed 4:3 and i cant screenshot on fullscreen stretch res but on 4:3 stretched they're really noticebale.

![image](https://github.com/Hypnootize/hypnotizehud/assets/141937232/db032b6d-3c32-41c5-b2e4-8427c6619961)
![image](https://github.com/Hypnootize/hypnotizehud/assets/141937232/4cecf682-bbf5-4989-8b47-4a13f876aec4)

**Comment by Hypnootize** [comment]
The last update fixed the Scrollbar not appearing in `sv_pure 1` servers as well as the Rank overlapping, I wasn't able to re-create the pixel gap problem you mentioned, I would like to know if it also happens with the default HUD as my HUD doesn't really do anything too different compared to it (at least background wise).

As for the other problems you mentioned, the expand/collapse and crafting filter icons can't be preloaded to work with `sv_pure 1` in any currently known way.
