### ISSUE TITLE
Menu change suggestion

### ISSUE THREAD

**Issue by LuhGeek4044** [Hypnootize/hypnotize-hud#57]
![received_959355041962456](https://github.com/Hypnootize/hypnotizehud/assets/141937232/592742ca-4986-4b3a-97aa-69f687fd3bb0)
![received_3798632403793926](https://github.com/Hypnootize/hypnotizehud/assets/141937232/d56432f9-c666-4cdf-90d3-f7df84f46fee)
![received_1201267534608482](https://github.com/Hypnootize/hypnotizehud/assets/141937232/df0dc67a-2424-483d-b4b0-d61062928e61)
![received_667844838578674](https://github.com/Hypnootize/hypnotizehud/assets/141937232/2dd1601a-2a69-4a82-93c0-eff69e794064)
image compression due to being digitally edited

**Comment by Hypnootize** [comment]
I appreciate the suggestion but I don't really feel like changing the design right now as it works fairly well, if I ever were to change it I would probably go with a completely different layout, compared to the current one, but as of now I'm working on other projects and I'm still fairly happy with how the HUD looks.

**Comment by LuhGeek4044** [comment]
to some extent i agree that it isnt neccesary to change the menu layout and leave it as is but it would be really nice if an option was available to have a less cluttered menu, some people think this way too such as this individual 
![image](https://github.com/Hypnootize/hypnotizehud/assets/141937232/3f6904b9-6358-44b5-ac07-d182dbc32dcf)
