### ISSUE TITLE
Short Stats

### ISSUE THREAD

**Issue by ZoronKrye** [Hypnootize/hypnotize-hud#59]
If I would like to replace a stat on the short stats scoreboard (say assists for healing done) how can I do that? I tried replacing the full stats healing piece into the nostats but then it was just blank on the short stat scoreboard, no title or anything.

**Comment by Hypnootize** [comment]
The easiest possible way would be to simply edit the `"labelText"` for both `"AssistsLabel"` `"AssistsWhite"` to instead feature the `"HealingLabel"` and `"HealingWhite"` ones.

The correct way of doing it might be a bit tricky as I pinned everything together, plus the MvM part would need to be adjusted as well. In short you would want to make `"AssistsLabel"` + `"AssistsWhite"` use all the values of `"HealingLabel"` and `"HealingWhite"` and vice versa.
