### ISSUE TITLE
Join Party button not display correctly

### ISSUE THREAD

**Issue by Gensokian** [Hypnootize/hypnotize-hud#6]
![unbenannt](https://user-images.githubusercontent.com/9213561/39322839-57963316-498b-11e8-9fe8-e8fd6a1ec71c.png)

**Comment by b7a** [comment]
I took the liberty to find a hotfix for this issue.

It's defined by MatchMakingDashboard.res -> "JoinNowButton"
Change "ypos" to "rs1-6" and "tall" to "16"
Should be good to go afterwards.
