### ISSUE TITLE
Hud's fonts not working at all

### ISSUE THREAD

**Issue by themercesletifer** [Hypnootize/hypnotize-hud#61]
Last year I always used hypnotisehud and it worked completely fine, and then around novemberish? when I got back into it again after a few months off the fonts stopped working. I reinstalled TF2 today and even grabbing latest version of the hud not a single one of the fonts work at all same as before. All the fonts are installed and have been for years now, tf2 base font works fine but every one of the Hud fonts don't work for me. Attached is what it looks like with the hud installed. Any assistance would be appreciated
![20240105013419_1](https://github.com/Hypnootize/hypnotizehud/assets/80370621/86abf99a-69fc-4ea2-9856-57b1a6b8220a)

**Comment by themercesletifer** [comment]
I will just quickly add aswell that I have looked around for a solution as some other people have had the same thing happen to them with different huds, but nobody has ever posted a fix as far as I can tell so I am at a loss as to what I can do.

**Comment by Hypnootize** [comment]
This is usually a side cause of installing fonts directly into Windows, if two fonts happen to have the same name the game won't have any way of differentiating the two and will end up prioritizing one of them even tho is not the one intended to.

As a solution you can try to open `C:/Windows/Fonts` and delete any font with `Rubik` in the name. 

You do not need to have them installed in Windows for the HUD to correctly use the fonts as long as they are installed correctly by the HUD developer inside the HUD files, in fact you should never need to as long as the developer did a good job installing them.

**Comment by themercesletifer** [comment]
Absolute Legend, that fixed it. In retrospect it was around November that I fully installed the Rubik font bundle while working on a project. Thank you so much, I appreciate the speedy assistance

**Comment by Hypnootize** [comment]
I'm glad it worked!
If you needed the font pack installed for other projects, or you need to install any font that is also used by TF2 in the future, you just have to make sure that there aren't multiple fonts with the same name (you can check what name they use with right click > properties > details > title).
If multiple fonts have the same name I usually just change them with FontForge, it's annoying but a very easy process at least. All you need to do is basically open the font in FontForge > Element > Info on Font and change the names there, then simply save it with File > Create Font and export it with the same file extensions it was already using.
