### ISSUE TITLE
Engineer HUD shows every structure as 'Dispenser'

### ISSUE THREAD

**Issue by jujar** [Hypnootize/hypnotize-hud#65]
On Linux, the engineer HUD shows every structure as dispenser. I don't have a Windows machine to confirm whether the behavior is the same on that platform.
![Screenshot_20240714_151800](https://github.com/user-attachments/assets/31240e9f-817a-45f3-b797-a434ed3b1e00)

**Comment by Hypnootize** [comment]
This is something that was already [reported](https://github.com/Hypnootize/hypnotizehud/issues/62) and it has also been [fixed](https://github.com/Hypnootize/hypnotizehud/commit/d41ab667d86058e68f8e90f3d37dc033346e0d21). Make sure to download the last version directly from this repo as the HUD might still be outdate in the other websites!
