### ISSUE TITLE
Chat Filter

### ISSUE THREAD

**Issue by Gensokian** [Hypnootize/hypnotize-hud#9]
In default TF2 there is a "Filter" button which allows for filtering of the chat to condense it down to callouts like "Medic!" Quite nice to have some peace and quiet whilst chillin
![image](https://user-images.githubusercontent.com/9213561/40254919-943b3954-5ae5-11e8-8f19-aaa7b23b6d48.png)

**Comment by Hypnootize** [comment]
You can still disable and enable these by using the console commands so i rather keep my chat really clean and as small as possible!
